[package]
name = "txn_processor"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

[dependencies]
csv = "1.3.0"
env_logger = "0.11.5"
itertools = "0.13.0"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"
